# CI file for GitLab

# Set defaults for variables
variables:
   PITCH_VERSION: "skeleton"
   PITCH_LRC_IMAGE_ALPINE: $CI_REGISTRY_IMAGE:pitch-${PITCH_VERSION}-alpine
   PITCH_LRC_IMAGE_DEBIAN: $CI_REGISTRY_IMAGE:pitch-${PITCH_VERSION}-debian
   PITCH_LRC_IMAGE_CENTOS7: $CI_REGISTRY_IMAGE:pitch-${PITCH_VERSION}-centos7
   PITCH_LRC_IMAGE: $CI_REGISTRY_IMAGE:pitch-${PITCH_VERSION}
   REPOSITORY: $CI_REGISTRY/hlacontainers/

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build

# Build LRC images
buildjob:
  stage: build
  script:
    - docker build -f docker/context/Dockerfile-pitch-alpine -t $PITCH_LRC_IMAGE_ALPINE --build-arg PITCH_VERSION=$PITCH_VERSION --build-arg PITCH_VERSION_STRING=$PITCH_LRC_IMAGE_ALPINE --build-arg REPOSITORY=$REPOSITORY docker/context
    - docker build -f docker/context/Dockerfile-pitch-debian -t $PITCH_LRC_IMAGE_DEBIAN --build-arg PITCH_VERSION=$PITCH_VERSION --build-arg PITCH_VERSION_STRING=$PITCH_LRC_IMAGE_DEBIAN --build-arg REPOSITORY=$REPOSITORY docker/context
    - docker build -f docker/context/Dockerfile-pitch-centos7 -t $PITCH_LRC_IMAGE_CENTOS7 --build-arg PITCH_VERSION=$PITCH_VERSION --build-arg PITCH_VERSION_STRING=$PITCH_LRC_IMAGE_CENTOS7 --build-arg REPOSITORY=$REPOSITORY docker/context
    - docker build -f docker/context/Dockerfile-pitch -t $PITCH_LRC_IMAGE --build-arg PITCH_VERSION=$PITCH_VERSION --build-arg PITCH_VERSION_STRING=$PITCH_LRC_IMAGE --build-arg REPOSITORY=$REPOSITORY docker/context
    - docker push $PITCH_LRC_IMAGE_ALPINE
    - docker push $PITCH_LRC_IMAGE_DEBIAN
    - docker push $PITCH_LRC_IMAGE_CENTOS7
    - docker push $PITCH_LRC_IMAGE
