version: '3'

services:

 ma-lrc-base-centos8:
  build:
   context: context
   dockerfile: Dockerfile-vtmak-centos8
   args:
   - VTMAK_VERSION=${VTMAK_VERSION}
   - REPOSITORY=${REPOSITORY}
  image: ${REPOSITORY}lrc:vtmak-${VTMAK_VERSION}-centos8-${JDK}
