version: '3'

services:
  
 po-lrc-base-alpine:
  build:
   context: context
   dockerfile: Dockerfile-portico-alpine
   args:
   - PORTICO_VERSION=${PORTICO_VERSION}
   - PORTICO_VERSION_STRING=lrc:portico-${PORTICO_VERSION}-alpine
  image: ${REPOSITORY}lrc:portico-${PORTICO_VERSION}-alpine

 po-lrc-base-debian:
  build:
   context: context
   dockerfile: Dockerfile-portico-debian
   args:
   - PORTICO_VERSION=${PORTICO_VERSION}
   - PORTICO_VERSION_STRING=lrc:portico-${PORTICO_VERSION}-debian
  image: ${REPOSITORY}lrc:portico-${PORTICO_VERSION}-debian

 po-lrc-base-centos7:
  build:
   context: context
   dockerfile: Dockerfile-portico-centos7
   args:
   - PORTICO_VERSION=${PORTICO_VERSION}
   - PORTICO_VERSION_STRING=lrc:portico-${PORTICO_VERSION}-centos7
  image: ${REPOSITORY}lrc:portico-${PORTICO_VERSION}-centos7

 po-lrc-base:
  build:
   context: context
   dockerfile: Dockerfile-portico
   args:
   - PORTICO_VERSION=${PORTICO_VERSION}
   - PORTICO_VERSION_STRING=lrc:portico-${PORTICO_VERSION}
  image: ${REPOSITORY}lrc:portico-${PORTICO_VERSION}
