version: '3'

services:

 pi-lrc-base-debian:
  build:
   context: context
   dockerfile: Dockerfile-pitch-debian
   args:
   - PITCH_VERSION=${PITCH_VERSION}
   - PITCH_VERSION_STRING=lrc:pitch-${PITCH_VERSION}-debian
   - REPOSITORY=${REPOSITORY}
  image: ${REPOSITORY}lrc:pitch-${PITCH_VERSION}-debian

 pi-lrc-base-centos7:
  build:
   context: context
   dockerfile: Dockerfile-pitch-centos7
   args:
   - PITCH_VERSION=${PITCH_VERSION}
   - PITCH_VERSION_STRING=lrc:pitch-${PITCH_VERSION}-centos7
   - REPOSITORY=${REPOSITORY}
  image: ${REPOSITORY}lrc:pitch-${PITCH_VERSION}-centos7

 pi-lrc-base:
  build:
   context: context
   dockerfile: Dockerfile-pitch
   args:
   - PITCH_VERSION=${PITCH_VERSION}
   - PITCH_VERSION_STRING=lrc:pitch-${PITCH_VERSION}
   - REPOSITORY=${REPOSITORY}
  image: ${REPOSITORY}lrc:pitch-${PITCH_VERSION}
