version: '3'

services:
  
 po-lrc-base-debian:
  build:
   context: context
   dockerfile: Dockerfile-portico-debian
   args:
   - PORTICO_VERSION=${PORTICO_VERSION}
  image: ${REPOSITORY}lrc:portico-${PORTICO_VERSION}-debian-${JDK}

 po-lrc-base-centos8:
  build:
   context: context
   dockerfile: Dockerfile-portico-centos8
   args:
   - PORTICO_VERSION=${PORTICO_VERSION}
  image: ${REPOSITORY}lrc:portico-${PORTICO_VERSION}-centos8-${JDK}
