version: '3'

services:

 pi-lrc-base-debian:
  build:
   context: context
   dockerfile: Dockerfile-pitch-debian
   args:
   - PITCH_VERSION=${PITCH_VERSION}
   - REPOSITORY=${REPOSITORY}
  image: ${REPOSITORY}lrc:pitch-${PITCH_VERSION}-debian-${JDK}

 pi-lrc-base-centos8:
  build:
   context: context
   dockerfile: Dockerfile-pitch-centos8
   args:
   - PITCH_VERSION=${PITCH_VERSION}
   - REPOSITORY=${REPOSITORY}
  image: ${REPOSITORY}lrc:pitch-${PITCH_VERSION}-centos8-${JDK}
