#
# Copyright 2020 Tom van den Berg (TNO, The Netherlands).
# SPDX-License-Identifier: Apache-2.0
#

# Set default for build-time ARGs
ARG REPOSITORY=hlacontainers/
ARG VTMAK_VERSION=skeleton
ARG VTMAK_VERSION_STRING=lrc:vtmak-${VTMAK_VERSION}-centos7

#########################
# Create Base image
#########################
FROM ${REPOSITORY}vtmak-rtiexec:${VTMAK_VERSION} AS base

# LRC files are installed here
ENV RTI_HOME=/usr/local/makRti

# Remove lib files we do not need in the next stage
RUN rm -rf $RTI_HOME/lib/gui
RUN rm -rf $RTI_HOME/bin/gui
RUN rm -f $RTI_HOME/lib/libRTI-NG_64.so
RUN find $RTI_HOME/bin -type f -not -name '*.xml' -delete

#########################
# Create Centos7 image
#########################
FROM centos:7

# Install Java
RUN yum update -y \
	&& yum -y install java-11-openjdk nc iproute \
	&& yum clean all

# LRC files are installed here
ARG RTI_HOME_FROM=/usr/local/makRti
ENV LRC_HOME=/usr/local/lrc
ENV RTI_HOME=${LRC_HOME}/code

# Ensure JAVA_HOME is set
ENV JAVA_HOME=/usr/lib/jvm/jre-openjdk

# Copy LRC files
COPY --from=base ${RTI_HOME_FROM}/bin/		${RTI_HOME}/bin/
COPY --from=base ${RTI_HOME_FROM}/lib/		${RTI_HOME}/lib/
COPY --from=base ${RTI_HOME_FROM}/include/	${RTI_HOME}/include/
COPY --from=base ${RTI_HOME_FROM}/rid.mtl	${RTI_HOME}/rid.mtl

# Set RID file
ENV RTI_RID_FILE=${RTI_HOME}/rid.mtl

# Set common environment variables
ENV LRC_CLASSPATH=${RTI_HOME}/lib/hla.jar
ENV LRC_LIBRARYPATH=${RTI_HOME}/lib/java:${RTI_HOME}/lib
ENV LD_LIBRARY_PATH=${LRC_LIBRARYPATH}:${LD_LIBRARY_PATH}
ENV CLASSPATH=${LRC_CLASSPATH}:${CLASSPATH}

# Do not start the assistant
ENV RTI_ASSISTANT_DISABLE=1

# Copy launch scripts
COPY vtmak/init.sh launch.sh ${LRC_HOME}/

# Set entrypoint and ensure it is executable
WORKDIR ${LRC_HOME}
ENTRYPOINT ["sh", "-c", "./launch.sh"]
RUN chmod +x launch.sh

# Set version from provided argument
ARG VTMAK_VERSION_STRING
ENV LRC_VERSION $VTMAK_VERSION_STRING
