#
# Copyright 2020 Tom van den Berg (TNO, The Netherlands).
# SPDX-License-Identifier: Apache-2.0
#

# Set default for build-time ARGs
ARG REPOSITORY=hlacontainers/
ARG PORTICO_VERSION=nightly-2016.05.28

##########################
# Image with LRC scripts #
##########################
FROM ${REPOSITORY}lrc-scripts as scripts

#############################
# Image with LRC data files #
#############################
FROM busybox AS base

ARG PORTICO_VERSION

# Install Portico LRC files
ADD portico/portico-${PORTICO_VERSION}-linux64.tar.gz /usr/local/portico/

# LRC files are installed here
ENV RTI_HOME=/usr/local/portico/portico-${PORTICO_VERSION}

# Remove files
RUN rm -rf \
	${RTI_HOME}/jre \
	${RTI_HOME}/*/jre \
	${RTI_HOME}/documentation \
	${RTI_HOME}/examples \
	${RTI_HOME}/bin \
	${RTI_HOME}/plugins \
	${RTI_HOME}/etc

##################
# LRC Base image #
##################
FROM openjdk:17-buster

ARG PORTICO_VERSION

# Install network utilities that are needed by the launch scripts (if used).
RUN apt-get update -y && apt-get install -y netcat

# Get application launch scripts
COPY --from=scripts /scripts /scripts/

# LRC files are installed here
ENV RTI_HOME=/usr/local/portico/portico-${PORTICO_VERSION}

# Copy LRC files
COPY --from=base ${RTI_HOME} ${RTI_HOME}/

# Default RID file
ENV PORTICO_RTI_RID_FILE=${RTI_HOME}/RTI.rid

# Set common environment variables
ENV	LD_LIBRARY_PATH=${RTI_HOME}/lib/gcc4:${JAVA_HOME}/lib/amd64:${JAVA_HOME}/lib/amd64/server:${LD_LIBRARY_PATH}
ENV	CLASSPATH=${RTI_HOME}/lib/portico.jar:${CLASSPATH}
