#
# Copyright 2020 Tom van den Berg (TNO, The Netherlands).
# SPDX-License-Identifier: Apache-2.0
#

# Set default for build-time ARGs
ARG PORTICO_VERSION=nightly-2016.05.28

#########################
# Create Base image
#########################
FROM busybox AS base

ARG PORTICO_VERSION

# Install Portico LRC files
ADD portico/portico-${PORTICO_VERSION}-linux64.tar.gz /usr/local/portico/

# LRC files are installed here
ENV RTI_HOME=/usr/local/portico/portico-${PORTICO_VERSION}

# Remove files
RUN rm -rf \
	${RTI_HOME}/jre \
	${RTI_HOME}/*/jre \
	${RTI_HOME}/documentation \
	${RTI_HOME}/examples \
	${RTI_HOME}/bin \
	${RTI_HOME}/plugins \
	${RTI_HOME}/etc

#########################
# Create Minimal image
#########################
FROM busybox

ARG PORTICO_VERSION

# LRC files are installed here
ENV RTI_HOME_FROM=/usr/local/portico/portico-${PORTICO_VERSION}
ENV LRC_HOME=/usr/local/lrc
ENV RTI_HOME=${LRC_HOME}/code

# Copy LRC files
COPY --from=base ${RTI_HOME_FROM} ${RTI_HOME}
	
# Copy launch scripts
ADD portico/init.sh launch.sh ${LRC_HOME}/
RUN chmod +x ./launch.sh

# Declare volume that can be mounted into other containers
VOLUME ["${LRC_HOME}"]

# Declare entrypoint to copy volume explicitly; needed in Kubernetes
ENTRYPOINT [ "sh", "-c", " \
   if [ -n \"$1\" ]; then \
      if [ -n \"$OPTS\" ]; then \
         cp $OPTS $LRC_HOME $1; \
      else \
         cp -a $LRC_HOME $1; \
      fi; \
      echo \"Copied $LRC_HOME to $1\"; \
   fi" , \
"--" ]
