#
# Copyright 2020 Tom van den Berg (TNO, The Netherlands).
# SPDX-License-Identifier: Apache-2.0
#

# Set default for build-time ARGs
ARG PORTICO_VERSION=nightly-2016.05.28
ARG PORTICO_VERSION_STRING=lrc:portico-${PORTICO_VERSION}-centos7

#########################
# Create Base image
#########################
FROM busybox AS base

ARG PORTICO_VERSION

# Install Portico LRC files
ADD portico/portico-${PORTICO_VERSION}-linux64.tar.gz /usr/local/portico/

# LRC files are installed here
ENV RTI_HOME=/usr/local/portico/portico-${PORTICO_VERSION}

# Remove files
RUN rm -rf \
	${RTI_HOME}/jre \
	${RTI_HOME}/*/jre \
	${RTI_HOME}/documentation \
	${RTI_HOME}/examples \
	${RTI_HOME}/bin \
	${RTI_HOME}/plugins \
	${RTI_HOME}/etc

#########################
# Create Centos image
#########################
FROM centos:7

ARG PORTICO_VERSION

#Install Java and netcat
RUN yum update -y \
	&& yum install -y java-11-openjdk nc iproute \
	&& yum clean all

# LRC files are installed here
ENV RTI_HOME_FROM=/usr/local/portico/portico-${PORTICO_VERSION}
ENV LRC_HOME=/usr/local/lrc
ENV RTI_HOME=${LRC_HOME}/code

# ensure JAVA_HOME is set
ENV JAVA_HOME=/usr/lib/jvm/jre-openjdk

# Copy LRC files
COPY --from=base ${RTI_HOME_FROM} ${RTI_HOME}
	
# Copy launch scripts
ADD portico/init.sh launch.sh ${LRC_HOME}/

# Set common environment variables
ENV LRC_CLASSPATH=${RTI_HOME}/lib/portico.jar
ENV	LRC_LIBRARYPATH=${RTI_HOME}/lib/gcc4:$JAVA_HOME/lib/amd64:$JAVA_HOME/lib/amd64/server
ENV	LD_LIBRARY_PATH=${LRC_LIBRARYPATH}:${LD_LIBRARY_PATH}
ENV	CLASSPATH=${LRC_CLASSPATH}:${CLASSPATH}

# Set entrypoint and ensure it is executable
WORKDIR ${LRC_HOME}
ENTRYPOINT ["/bin/sh", "./launch.sh"]
RUN chmod +x ./launch.sh

# Set version from provided argument
ARG PORTICO_VERSION_STRING
ENV LRC_VERSION $PORTICO_VERSION_STRING
